

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on the default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: generalpurouse
      MONGO_INITDB_ROOT_PASSWORD: YpIoSrJfaGdbKYGs
      

    volumes:
      - mongodbdata:/data/db  # Persist MongoDB data

volumes:
  mongodbdata:
